### ISSUE TITLE
CT phetioID already registered

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/coulombs-law#108]
```
coulombs-law : phet-io-fuzz : require.js : load
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioID already registered: coulombsLaw.macroScreen.coulombsLawMacroScreen.view.scientificNotationCheckbox.enabledProperty
Error: Assertion failed: phetioID already registered: coulombsLaw.macroScreen.coulombsLawMacroScreen.view.scientificNotationCheckbox.enabledProperty
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/assert/js/assert.js:22:13)
    at PhetioEngine.phetioObjectAdded (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/phet-io/js/phetioEngine.js?bust=1562064040303:366:36)
    at Object.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/phet-io/js/phetioEngine.js?bust=1562064040303:450:51)
    at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/tandem/js/Tandem.js?bust=1562064040303:144:40)
    at LinkedElement.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/tandem/js/PhetioObject.js?bust=1562064040303:306:19)
    at new PhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/tandem/js/PhetioObject.js?bust=1562064040303:132:12)
    at new LinkedElement (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/tandem/js/PhetioObject.js?bust=1562064040303:481:7)
    at Checkbox.addLinkedElement (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/tandem/js/PhetioObject.js?bust=1562064040303:388:35)
    at new Checkbox (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/sun/js/Checkbox.js?bust=1562064040303:149:12)
    at new VerticalCheckboxGroup (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/sun/js/VerticalCheckboxGroup.js?bust=1562064040303:67:22)
id: Bayes Chrome
Approximately 7/2/2019, 1:57:26 AM
coulombs-law : phet-io-fuzz : require.js : load
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioID already registered: coulombsLaw.macroScreen.coulombsLawMacroScreen.view.scientificNotationCheckbox.enabledProperty
Error: Assertion failed: phetioID already registered: coulombsLaw.macroScreen.coulombsLawMacroScreen.view.scientificNotationCheckbox.enabledProperty
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/assert/js/assert.js:22:13)
    at PhetioEngine.phetioObjectAdded (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/phet-io/js/phetioEngine.js?bust=1562079201838:366:36)
    at Object.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/phet-io/js/phetioEngine.js?bust=1562079201838:450:51)
    at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/tandem/js/Tandem.js?bust=1562079201838:144:40)
    at LinkedElement.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/tandem/js/PhetioObject.js?bust=1562079201838:306:19)
    at new PhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/tandem/js/PhetioObject.js?bust=1562079201838:132:12)
    at new LinkedElement (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/tandem/js/PhetioObject.js?bust=1562079201838:481:7)
    at Checkbox.addLinkedElement (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/tandem/js/PhetioObject.js?bust=1562079201838:388:35)
    at new Checkbox (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/sun/js/Checkbox.js?bust=1562079201838:149:12)
    at new VerticalCheckboxGroup (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/sun/js/VerticalCheckboxGroup.js?bust=1562079201838:67:22)
id: Bayes Chrome
Approximately 7/2/2019, 1:57:26 AM
coulombs-law : phet-io-fuzz : require.js : run
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioID already registered: coulombsLaw.macroScreen.coulombsLawMacroScreen.view.scientificNotationCheckbox.enabledProperty
Error: Assertion failed: phetioID already registered: coulombsLaw.macroScreen.coulombsLawMacroScreen.view.scientificNotationCheckbox.enabledProperty
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/assert/js/assert.js:22:13)
    at PhetioEngine.phetioObjectAdded (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/phet-io/js/phetioEngine.js?bust=1562064040303:366:36)
    at Object.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/phet-io/js/phetioEngine.js?bust=1562064040303:450:51)
    at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/tandem/js/Tandem.js?bust=1562064040303:144:40)
    at LinkedElement.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/tandem/js/PhetioObject.js?bust=1562064040303:306:19)
    at new PhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/tandem/js/PhetioObject.js?bust=1562064040303:132:12)
    at new LinkedElement (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/tandem/js/PhetioObject.js?bust=1562064040303:481:7)
    at Checkbox.addLinkedElement (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/tandem/js/PhetioObject.js?bust=1562064040303:388:35)
    at new Checkbox (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/sun/js/Checkbox.js?bust=1562064040303:149:12)
    at new VerticalCheckboxGroup (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/sun/js/VerticalCheckboxGroup.js?bust=1562064040303:67:22)
id: Bayes Chrome
Approximately 7/2/2019, 1:57:26 AM
coulombs-law : phet-io-fuzz : require.js : run
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioID already registered: coulombsLaw.macroScreen.coulombsLawMacroScreen.view.scientificNotationCheckbox.enabledProperty
Error: Assertion failed: phetioID already registered: coulombsLaw.macroScreen.coulombsLawMacroScreen.view.scientificNotationCheckbox.enabledProperty
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/assert/js/assert.js:22:13)
    at PhetioEngine.phetioObjectAdded (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/phet-io/js/phetioEngine.js?bust=1562079201838:366:36)
    at Object.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/phet-io/js/phetioEngine.js?bust=1562079201838:450:51)
    at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/tandem/js/Tandem.js?bust=1562079201838:144:40)
    at LinkedElement.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/tandem/js/PhetioObject.js?bust=1562079201838:306:19)
    at new PhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/tandem/js/PhetioObject.js?bust=1562079201838:132:12)
    at new LinkedElement (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/tandem/js/PhetioObject.js?bust=1562079201838:481:7)
    at Checkbox.addLinkedElement (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/tandem/js/PhetioObject.js?bust=1562079201838:388:35)
    at new Checkbox (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/sun/js/Checkbox.js?bust=1562079201838:149:12)
    at new VerticalCheckboxGroup (https://bayes.colorado.edu/continuous-testing/snapshot-1562054246154/sun/js/VerticalCheckboxGroup.js?bust=1562079201838:67:22)
id: Bayes Chrome
Approximately 7/2/2019, 1:57:26 AM
```

**Comment by zepumph** [comment]
Yes thank you. This was from and fix as part of https://github.com/phetsims/inverse-square-law-common/issues/66
