### ISSUE TITLE
CT API mismatches present

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/coulombs-law#110]
```
coulombs-law : phet-io-fuzz : require.js : load
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: api mismatches present:

coulombsLaw.macroScreen.coulombsLawMacroScreen.model.charge1.valueProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.,
coulombsLaw.macroScreen.coulombsLawMacroScreen.model.charge2.valueProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.,
coulombsLaw.atomicScreen.coulombsLawAtomicScreen.model.charge1.valueProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.,
coulombsLaw.atomicScreen.coulombsLawAtomicScreen.model.charge2.valueProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
Error: Assertion failed: api mismatches present:

coulombsLaw.macroScreen.coulombsLawMacroScreen.model.charge1.valueProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.,
coulombsLaw.macroScreen.coulombsLawMacroScreen.model.charge2.valueProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.,
coulombsLaw.atomicScreen.coulombsLawAtomicScreen.model.charge1.valueProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.,
coulombsLaw.atomicScreen.coulombsLawAtomicScreen.model.charge2.valueProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/assert/js/assert.js:22:13)
    at PhetioAPIValidation.assertOutIfErrorsPresent (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/tandem/js/phetioAPIValidation.js?:290:9)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/tandem/js/phetioAPIValidation.js?:174:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/phet-io/js/phetioEngine.js?:138:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/axon/js/TinyEmitter.js?:59:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/axon/js/Emitter.js?:35:31
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/axon/js/Action.js?:254:20)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/axon/js/Emitter.js?:60:21)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/joist/js/Sim.js?:845:50
id: Bayes Chrome
Approximately 8/6/2019, 3:47:32 AM
coulombs-law : phet-io-fuzz : require.js : run
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: api mismatches present:

coulombsLaw.macroScreen.coulombsLawMacroScreen.model.charge1.valueProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.,
coulombsLaw.macroScreen.coulombsLawMacroScreen.model.charge2.valueProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.,
coulombsLaw.atomicScreen.coulombsLawAtomicScreen.model.charge1.valueProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.,
coulombsLaw.atomicScreen.coulombsLawAtomicScreen.model.charge2.valueProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
Error: Assertion failed: api mismatches present:

coulombsLaw.macroScreen.coulombsLawMacroScreen.model.charge1.valueProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.,
coulombsLaw.macroScreen.coulombsLawMacroScreen.model.charge2.valueProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.,
coulombsLaw.atomicScreen.coulombsLawAtomicScreen.model.charge1.valueProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.,
coulombsLaw.atomicScreen.coulombsLawAtomicScreen.model.charge2.valueProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/assert/js/assert.js:22:13)
    at PhetioAPIValidation.assertOutIfErrorsPresent (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/tandem/js/phetioAPIValidation.js?:290:9)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/tandem/js/phetioAPIValidation.js?:174:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/phet-io/js/phetioEngine.js?:138:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/axon/js/TinyEmitter.js?:59:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/axon/js/Emitter.js?:35:31
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/axon/js/Action.js?:254:20)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/axon/js/Emitter.js?:60:21)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/joist/js/Sim.js?:845:50
id: Bayes Chrome
Approximately 8/6/2019, 3:47:32 AM
coulombs-law : phet-io-tests : assert
7 out of 9 tests passed. 2 failed.
SimTests: coulombs-law: iframe api failed:
Uncaught Error: Uncaught Error: Assertion failed: api mismatches present:

coulombsLaw.macroScreen.coulombsLawMacroScreen.model.charge1.valueProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.,
coulombsLaw.macroScreen.coulombsLawMacroScreen.model.charge2.valueProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.,
coulombsLaw.atomicScreen.coulombsLawAtomicScreen.model.charge1.valueProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.,
coulombsLaw.atomicScreen.coulombsLawAtomicScreen.model.charge2.valueProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/phet-io-wrappers/js/tests/SimTests.js?:341

SimTests: coulombs-law: event indexing failed:
Uncaught Error: Uncaught Error: Assertion failed: api mismatches present:

coulombsLaw.macroScreen.coulombsLawMacroScreen.model.charge1.valueProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.,
coulombsLaw.macroScreen.coulombsLawMacroScreen.model.charge2.valueProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.,
coulombsLaw.atomicScreen.coulombsLawAtomicScreen.model.charge1.valueProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.,
coulombsLaw.atomicScreen.coulombsLawAtomicScreen.model.charge2.valueProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/phet-io-wrappers/js/tests/SimTests.js?:531


id: Bayes Chrome
Approximately 8/6/2019, 3:47:32 AM
coulombs-law : phet-io-tests : no-assert
7 out of 9 tests passed. 2 failed.
SimTests: coulombs-law: iframe api failed:
Uncaught Error: Uncaught Error: Assertion failed: api mismatches present:

coulombsLaw.macroScreen.coulombsLawMacroScreen.model.charge1.valueProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.,
coulombsLaw.macroScreen.coulombsLawMacroScreen.model.charge2.valueProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.,
coulombsLaw.atomicScreen.coulombsLawAtomicScreen.model.charge1.valueProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.,
coulombsLaw.atomicScreen.coulombsLawAtomicScreen.model.charge2.valueProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/phet-io-wrappers/js/tests/SimTests.js?:341

SimTests: coulombs-law: event indexing failed:
Uncaught Error: Uncaught Error: Assertion failed: api mismatches present:

coulombsLaw.macroScreen.coulombsLawMacroScreen.model.charge1.valueProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.,
coulombsLaw.macroScreen.coulombsLawMacroScreen.model.charge2.valueProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.,
coulombsLaw.atomicScreen.coulombsLawAtomicScreen.model.charge1.valueProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.,
coulombsLaw.atomicScreen.coulombsLawAtomicScreen.model.charge2.valueProperty:  2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/phet-io-wrappers/js/tests/SimTests.js?:531


id: Bayes Chrome
Approximately 8/6/2019, 3:47:32 AM
```

**Comment by zepumph** [comment]
From commits in https://github.com/phetsims/gravity-force-lab/issues/76. Closing
