### ISSUE TITLE
CT cannot read property addToBack of undefined

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/coulombs-law#122]
```
coulombs-law : interactive-description-fuzzBoard : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603281270514/coulombs-law/build/phet/coulombs-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1603281270514%22%2C%22timestamp%22%3A1603284393915%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: Cannot read property 'addToBack' of undefined
TypeError: Cannot read property 'addToBack' of undefined
at QB.endDrag [as _endChange] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603281270514/coulombs-law/build/phet/coulombs-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1603281270514%22%2C%22timestamp%22%3A1603284393915%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:854:2200904)
at QB.onInteractionEnd (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603281270514/coulombs-law/build/phet/coulombs-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1603281270514%22%2C%22timestamp%22%3A1603284393915%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:854:1032757)
at QB.handleBlur (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603281270514/coulombs-law/build/phet/coulombs-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1603281270514%22%2C%22timestamp%22%3A1603284393915%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:854:1032643)
at no.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603281270514/coulombs-law/build/phet/coulombs-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1603281270514%22%2C%22timestamp%22%3A1603284393915%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:854:513923)
at no.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603281270514/coulombs-law/build/phet/coulombs-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1603281270514%22%2C%22timestamp%22%3A1603284393915%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:854:514098)
at no.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603281270514/coulombs-law/build/phet/coulombs-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1603281270514%22%2C%22timestamp%22%3A1603284393915%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:854:513688)
at no.dispatchA11yEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603281270514/coulombs-law/build/phet/coulombs-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1603281270514%22%2C%22timestamp%22%3A1603284393915%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:854:510099)
at focusoutAction.z.phetioPlayback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603281270514/coulombs-law/build/phet/coulombs-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1603281270514%22%2C%22timestamp%22%3A1603284393915%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:854:505560)
at H.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603281270514/coulombs-law/build/phet/coulombs-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1603281270514%22%2C%22timestamp%22%3A1603284393915%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:854:53635)
at HTMLDivElement.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603281270514/coulombs-law/build/phet/coulombs-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1603281270514%22%2C%22timestamp%22%3A1603284393915%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:854:507751)
id: Bayes Chrome
Snapshot from 10/21/2020, 5:54:30 AM

----------------------------------

coulombs-law : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603281270514/coulombs-law/coulombs-law_en.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1603281270514%22%2C%22timestamp%22%3A1603282435068%7D&brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: Cannot read property 'addToBack' of undefined
TypeError: Cannot read property 'addToBack' of undefined
at ChargeNode.endDrag [as _endChange] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603281270514/inverse-square-law-common/js/view/ISLCObjectNode.js:400:48)
at ChargeNode.onInteractionEnd (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603281270514/sun/js/accessibility/AccessibleValueHandler.js:676:14)
at ChargeNode.handleKeyUp (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603281270514/sun/js/accessibility/AccessibleValueHandler.js:561:20)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603281270514/scenery/js/input/Input.js:1825:25)
at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603281270514/scenery/js/input/Input.js:1857:12)
at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603281270514/scenery/js/input/Input.js:1783:10)
at Input.dispatchA11yEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603281270514/scenery/js/input/Input.js:1039:12)
at Input.keyupAction.Action.phetioPlayback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603281270514/scenery/js/input/Input.js:712:14)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603281270514/axon/js/Action.js:225:18)
at HTMLDivElement.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603281270514/scenery/js/input/Input.js:741:30)
id: Bayes Chrome
Snapshot from 10/21/2020, 5:54:30 AM
```

**Comment by KatieWoe** [comment]
Duplicate of https://github.com/phetsims/utterance-queue/issues/15. Closing
