### ISSUE TITLE
CT value failed isValidValue -0.01

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/coulombs-law#123]
```
coulombs-law : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614703718286/coulombs-law/coulombs-law_en.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1614703718286%22%2C%22timestamp%22%3A1614704472348%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: value failed isValidValue: -0.01
Error: Assertion failed: value failed isValidValue: -0.01
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614703718286/assert/js/assert.js:25:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614703718286/axon/js/ValidatorDef.js:307:39)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614703718286/axon/js/validate.js:25:26)
at NumberProperty.validateNumberProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614703718286/axon/js/NumberProperty.js:105:9)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614703718286/axon/js/NumberProperty.js:138:12
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614703718286/axon/js/TinyEmitter.js:86:18)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614703718286/axon/js/Property.js:294:25)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614703718286/axon/js/Property.js:191:14)
at NumberProperty.reset (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614703718286/axon/js/Property.js:357:10)
at NumberProperty.reset (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614703718286/axon/js/NumberProperty.js:182:11)
id: Bayes Chrome
Snapshot from 3/2/2021, 9:48:38 AM

----------------------------------

coulombs-law : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614703718286/coulombs-law/coulombs-law_en.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1614703718286%22%2C%22timestamp%22%3A1614705112803%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: value failed isValidValue: -2e-11
Error: Assertion failed: value failed isValidValue: -2e-11
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614703718286/assert/js/assert.js:25:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614703718286/axon/js/ValidatorDef.js:307:39)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614703718286/axon/js/validate.js:25:26)
at NumberProperty.validateNumberProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614703718286/axon/js/NumberProperty.js:105:9)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614703718286/axon/js/NumberProperty.js:138:12
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614703718286/axon/js/TinyEmitter.js:86:18)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614703718286/axon/js/Property.js:294:25)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614703718286/axon/js/Property.js:191:14)
at NumberProperty.reset (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614703718286/axon/js/Property.js:357:10)
at NumberProperty.reset (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614703718286/axon/js/NumberProperty.js:182:11)
id: Bayes Chrome
Snapshot from 3/2/2021, 9:48:38 AM

----------------------------------

coulombs-law : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614703718286/phet-io-wrappers/mirror-inputs/?sim=coulombs-law&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1614703718286%22%2C%22timestamp%22%3A1614705283781%7D
Uncaught Error: Uncaught Error: Assertion failed: value failed isValidValue: -2e-11
Error: Assertion failed: value failed isValidValue: -2e-11
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614703718286/assert/js/assert.js:25:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614703718286/axon/js/ValidatorDef.js:307:39)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614703718286/axon/js/validate.js:25:26)
at NumberProperty.validateNumberProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614703718286/axon/js/NumberProperty.js:105:9)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614703718286/axon/js/NumberProperty.js:138:12
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614703718286/axon/js/TinyEmitter.js:86:18)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614703718286/axon/js/Property.js:294:25)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614703718286/axon/js/Property.js:191:14)
at NumberProperty.reset (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614703718286/axon/js/Property.js:357:10)
at NumberProperty.reset (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614703718286/axon/js/NumberProperty.js:182:11)
id: Bayes Chrome
Snapshot from 3/2/2021, 9:48:38 AM
```

**Comment by zepumph** [comment]
Covered by https://github.com/phetsims/inverse-square-law-common/issues/83

**Comment by zepumph** [comment]
Fixed by https://github.com/phetsims/inverse-square-law-common/commit/5115d720fec482959037568f454a4ace745590c9
