### ISSUE TITLE
CT passed-in thumbNode must have the correct tandem

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/coulombs-law#124]
```
coulombs-law : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/phet-io-wrappers/mirror-inputs/?sim=coulombs-law&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1618238625034%22%2C%22timestamp%22%3A1618242654822%7D
Uncaught Error: Uncaught Error: Assertion failed: Passed-in thumbNode must have the correct tandem. Expected: coulombsLaw.macroScreen.coulombsLawMacroScreen.view.charge1Control.numberControl.slider.thumb, actual: coulombsLaw.macroScreen.coulombsLawMacroScreen.view.charge1Control.chargeControlsSliderThumb
Error: Assertion failed: Passed-in thumbNode must have the correct tandem. Expected: coulombsLaw.macroScreen.coulombsLawMacroScreen.view.charge1Control.numberControl.slider.thumb, actual: coulombsLaw.macroScreen.coulombsLawMacroScreen.view.charge1Control.chargeControlsSliderThumb
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/assert/js/assert.js:25:13)
at new Slider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/sun/js/Slider.js:200:17)
at new HSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/sun/js/HSlider.js:27:5)
at new NumberControl (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/scenery-phet/js/NumberControl.js:250:19)
at new ISLCObjectControlPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/inverse-square-law-common/js/view/ISLCObjectControlPanel.js:123:27)
at new ChargeControl (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/coulombs-law/js/common/view/ChargeControl.js:85:5)
at new CoulombsLawCommonView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/coulombs-law/js/common/view/CoulombsLawCommonView.js:76:28)
at new CoulombsLawMacroView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/coulombs-law/js/macro/view/CoulombsLawMacroView.js:48:5)
at CoulombsLawMacroScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/coulombs-law/js/macro/CoulombsLawMacroScreen.js:47:16)
at CoulombsLawMacroScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/joist/js/Screen.js:253:23)
id: Bayes Chrome
Snapshot from 4/12/2021, 8:43:45 AM

----------------------------------

coulombs-law : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/phet-io-wrappers/phet-io-wrappers-tests.html?sim=coulombs-law
3 out of 4 tests passed. 1 failed.
SimTests: coulombs-law: iframe api failed:
Uncaught Error: Uncaught Error: Assertion failed: Passed-in thumbNode must have the correct tandem. Expected: coulombsLaw.macroScreen.coulombsLawMacroScreen.view.charge1Control.numberControl.slider.thumb, actual: coulombsLaw.macroScreen.coulombsLawMacroScreen.view.charge1Control.chargeControlsSliderThumb
Error: Assertion failed: Passed-in thumbNode must have the correct tandem. Expected: coulombsLaw.macroScreen.coulombsLawMacroScreen.view.charge1Control.numberControl.slider.thumb, actual: coulombsLaw.macroScreen.coulombsLawMacroScreen.view.charge1Control.chargeControlsSliderThumb
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/assert/js/assert.js:25:13)
at new Slider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/sun/js/Slider.js:200:17)
at new HSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/sun/js/HSlider.js:27:5)
at new NumberControl (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/scenery-phet/js/NumberControl.js:250:19)
at new ISLCObjectControlPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/inverse-square-law-common/js/view/ISLCObjectControlPanel.js:123:27)
at new ChargeControl (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/coulombs-law/js/common/view/ChargeControl.js:85:5)
at new CoulombsLawCommonView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/coulombs-law/js/common/view/CoulombsLawCommonView.js:76:28)
at new CoulombsLawMacroView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/coulombs-law/js/macro/view/CoulombsLawMacroView.js:48:5)
at CoulombsLawMacroScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/coulombs-law/js/macro/CoulombsLawMacroScreen.js:47:16)
at CoulombsLawMacroScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/joist/js/Screen.js:253:23)

Uncaught Error: Uncaught Error: Assertion failed: Passed-in thumbNode must have the correct tandem. Expected: coulombsLaw.macroScreen.coulombsLawMacroScreen.view.charge1Control.numberControl.slider.thumb, actual: coulombsLaw.macroScreen.coulombsLawMacroScreen.view.charge1Control.chargeControlsSliderThumbError: Assertion failed: Passed-in thumbNode must have the correct tandem. Expected: coulombsLaw.macroScreen.coulombsLawMacroScreen.view.charge1Control.numberControl.slider.thumb, actual: coulombsLaw.macroScreen.coulombsLawMacroScreen.view.charge1Control.chargeControlsSliderThumb
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/assert/js/assert.js:25:13)
at new Slider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/sun/js/Slider.js:200:17)
at new HSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/sun/js/HSlider.js:27:5)
at new NumberControl (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/scenery-phet/js/NumberControl.js:250:19)
at new ISLCObjectControlPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/inverse-square-law-common/js/view/ISLCObjectControlPanel.js:123:27)
at new ChargeControl (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/coulombs-law/js/common/view/ChargeControl.js:85:5)
at new CoulombsLawCommonView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/coulombs-law/js/common/view/CoulombsLawCommonView.js:76:28)
at new CoulombsLawMacroView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/coulombs-law/js/macro/view/CoulombsLawMacroView.js:48:5)
at CoulombsLawMacroScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/coulombs-law/js/macro/CoulombsLawMacroScreen.js:47:16)
at CoulombsLawMacroScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1618238625034/joist/js/Screen.js:253:23)
id: Bayes Chrome
Snapshot from 4/12/2021, 8:43:45 AM
```

**Comment by zepumph** [comment]
Looks like the same trouble as in https://github.com/phetsims/sun/issues/694.

**Comment by zepumph** [comment]
Fixed in a bad way. Closing, to be better sorted over in the general issue.
