### ISSUE TITLE
CT build failed with status code 1

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/coulombs-law#129]
```
coulombs-law : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (coulombs-law, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 6167ms
>> Production minification complete: 36287ms (2702628 bytes)
>> Debug minification complete: 1ms (7086402 bytes)
Building brand: phet-io
>> Webpack build complete: 4929ms
>> Production minification complete: 32977ms (2727782 bytes)
>> Debug minification complete: 32880ms (3012056 bytes)
>> No client guides found at ../phet-io-client-guides/coulombs-law/, no guides being built.
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION]: Full API expected but not created from puppeteer step, likely caused by https://github.com/phetsims/chipper/issues/1022.
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1629275039864/chipper/js/grunt/copySupplementalPhetioFiles.js:316:5)
at async module.exports (/data/share/phet/continuous-testing/ct-snapshots/1629275039864/chipper/js/grunt/buildRunnable.js:356:5)
at async /data/share/phet/continuous-testing/ct-snapshots/1629275039864/chipper/js/grunt/Gruntfile.js:254:11
at async wrap (/data/share/phet/continuous-testing/ct-snapshots/1629275039864/chipper/js/grunt/Gruntfile.js:71:7)
Full Error details:
AssertionError [ERR_ASSERTION]: Full API expected but not created from puppeteer step, likely caused by https://github.com/phetsims/chipper/issues/1022.

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Error in fulfilling chunk Promise: [Error: TypeError: Cannot read properties of undefined (reading 'length')
at Object.numberOfDecimalPlaces (http://localhost:41935/coulombs-law/build/phet-io/coulombs-law_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:857:95640)
at Nw.snapToGrid (http://localhost:41935/coulombs-law/build/phet-io/coulombs-law_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:857:1211636)
at Nw.getSumRadiusWithSeparation (http://localhost:41935/coulombs-law/build/phet-io/coulombs-law_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:857:1211137)
at Nw.getObjectMaxPosition (http://localhost:41935/coulombs-law/build/phet-io/coulombs-law_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:857:1211188)
at h (http://localhost:41935/coulombs-law/build/phet-io/coulombs-law_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:857:1208077)
at http://localhost:41935/coulombs-law/build/phet-io/coulombs-law_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:857:1208233
at new g (http://localhost:41935/coulombs-law/build/phet-io/coulombs-law_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:857:4778)
at Function.multilink (http://localhost:41935/coulombs-law/build/phet-io/coulombs-law_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:857:8690)
at new Qw (http://localhost:41935/coulombs-law/build/phet-io/coulombs-law_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:857:1208178)
at new Uw (http://localhost:41935/coulombs-law/build/phet-io/coulombs-law_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:857:1212340)]
Snapshot from 8/18/2021, 2:23:59 AM

----------------------------------

coulombs-law : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/coulombs-law/coulombs-law_en.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1629275039864%22%2C%22timestamp%22%3A1629276745110%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: scientific notation is not supported: 1e-12
Error: Assertion failed: scientific notation is not supported: 1e-12
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/assert/js/assert.js:25:13)
at Object.numberOfDecimalPlaces (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/dot/js/Utils.js:835:17)
at CoulombsLawAtomicModel.snapToGrid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:427:36)
at CoulombsLawAtomicModel.getSumRadiusWithSeparation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:354:17)
at CoulombsLawAtomicModel.getObjectMaxPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:366:28)
at updateRange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:100:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:109:7
at new Multilink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/axon/js/Multilink.js:62:7)
at Function.multilink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/axon/js/Property.js:533:12)
at new ISLCModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:108:14)
id: Bayes Chrome
Snapshot from 8/18/2021, 2:23:59 AM

----------------------------------

coulombs-law : interactive-description-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/coulombs-law/coulombs-law_en.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1629275039864%22%2C%22timestamp%22%3A1629276306945%7D&brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught Error: Assertion failed: scientific notation is not supported: 1e-12
Error: Assertion failed: scientific notation is not supported: 1e-12
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/assert/js/assert.js:25:13)
at Object.numberOfDecimalPlaces (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/dot/js/Utils.js:835:17)
at CoulombsLawAtomicModel.snapToGrid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:427:36)
at CoulombsLawAtomicModel.getSumRadiusWithSeparation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:354:17)
at CoulombsLawAtomicModel.getObjectMaxPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:366:28)
at updateRange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:100:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:109:7
at new Multilink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/axon/js/Multilink.js:62:7)
at Function.multilink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/axon/js/Property.js:533:12)
at new ISLCModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:108:14)
id: Bayes Chrome
Snapshot from 8/18/2021, 2:23:59 AM

----------------------------------

coulombs-law : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/coulombs-law/coulombs-law_en.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1629275039864%22%2C%22timestamp%22%3A1629277353954%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: scientific notation is not supported: 1e-12
Error: Assertion failed: scientific notation is not supported: 1e-12
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/assert/js/assert.js:25:13)
at Object.numberOfDecimalPlaces (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/dot/js/Utils.js:835:17)
at CoulombsLawAtomicModel.snapToGrid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:427:36)
at CoulombsLawAtomicModel.getSumRadiusWithSeparation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:354:17)
at CoulombsLawAtomicModel.getObjectMaxPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:366:28)
at updateRange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:100:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:109:7
at new Multilink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/axon/js/Multilink.js:62:7)
at Function.multilink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/axon/js/Property.js:533:12)
at new ISLCModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:108:14)
id: Bayes Chrome
Snapshot from 8/18/2021, 2:23:59 AM

----------------------------------

coulombs-law : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/coulombs-law/coulombs-law_en.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1629275039864%22%2C%22timestamp%22%3A1629276997084%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: scientific notation is not supported: 1e-12
Error: Assertion failed: scientific notation is not supported: 1e-12
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/assert/js/assert.js:25:13)
at Object.numberOfDecimalPlaces (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/dot/js/Utils.js:835:17)
at CoulombsLawAtomicModel.snapToGrid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:427:36)
at CoulombsLawAtomicModel.getSumRadiusWithSeparation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:354:17)
at CoulombsLawAtomicModel.getObjectMaxPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:366:28)
at updateRange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:100:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:109:7
at new Multilink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/axon/js/Multilink.js:62:7)
at Function.multilink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/axon/js/Property.js:533:12)
at new ISLCModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:108:14)
id: Bayes Chrome
Snapshot from 8/18/2021, 2:23:59 AM

----------------------------------

coulombs-law : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/coulombs-law/coulombs-law_en.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1629275039864%22%2C%22timestamp%22%3A1629276316582%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: scientific notation is not supported: 1e-12
Error: Assertion failed: scientific notation is not supported: 1e-12
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/assert/js/assert.js:25:13)
at Object.numberOfDecimalPlaces (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/dot/js/Utils.js:835:17)
at CoulombsLawAtomicModel.snapToGrid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:427:36)
at CoulombsLawAtomicModel.getSumRadiusWithSeparation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:354:17)
at CoulombsLawAtomicModel.getObjectMaxPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:366:28)
at updateRange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:100:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:109:7
at new Multilink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/axon/js/Multilink.js:62:7)
at Function.multilink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/axon/js/Property.js:533:12)
at new ISLCModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:108:14)
id: Bayes Chrome
Snapshot from 8/18/2021, 2:23:59 AM

----------------------------------

coulombs-law : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/phet-io-wrappers/mirror-inputs/?sim=coulombs-law&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1629275039864%22%2C%22timestamp%22%3A1629276432308%7D
Uncaught Error: Uncaught Error: Assertion failed: scientific notation is not supported: 1e-12
Error: Assertion failed: scientific notation is not supported: 1e-12
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/assert/js/assert.js:25:13)
at Object.numberOfDecimalPlaces (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/dot/js/Utils.js:835:17)
at CoulombsLawAtomicModel.snapToGrid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:427:36)
at CoulombsLawAtomicModel.getSumRadiusWithSeparation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:354:17)
at CoulombsLawAtomicModel.getObjectMaxPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:366:28)
at updateRange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:100:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:109:7
at new Multilink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/axon/js/Multilink.js:62:7)
at Function.multilink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/axon/js/Property.js:533:12)
at new ISLCModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:108:14)
id: Bayes Chrome
Snapshot from 8/18/2021, 2:23:59 AM

----------------------------------

coulombs-law : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/phet-io-wrappers/phet-io-wrappers-tests.html?sim=coulombs-law&phetioDebug
3 out of 4 tests passed. 1 failed.
SimTests: coulombs-law: iframe API failed:
Uncaught Error: Uncaught Error: Assertion failed: scientific notation is not supported: 1e-12
Error: Assertion failed: scientific notation is not supported: 1e-12
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/assert/js/assert.js:25:13)
at Object.numberOfDecimalPlaces (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/dot/js/Utils.js:835:17)
at CoulombsLawAtomicModel.snapToGrid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:427:36)
at CoulombsLawAtomicModel.getSumRadiusWithSeparation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:354:17)
at CoulombsLawAtomicModel.getObjectMaxPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:366:28)
at updateRange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:100:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:109:7
at new Multilink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/axon/js/Multilink.js:62:7)
at Function.multilink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/axon/js/Property.js:533:12)
at new ISLCModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:108:14)

Uncaught Error: Uncaught Error: Assertion failed: scientific notation is not supported: 1e-12Error: Assertion failed: scientific notation is not supported: 1e-12
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/assert/js/assert.js:25:13)
at Object.numberOfDecimalPlaces (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/dot/js/Utils.js:835:17)
at CoulombsLawAtomicModel.snapToGrid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:427:36)
at CoulombsLawAtomicModel.getSumRadiusWithSeparation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:354:17)
at CoulombsLawAtomicModel.getObjectMaxPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:366:28)
at updateRange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:100:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:109:7
at new Multilink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/axon/js/Multilink.js:62:7)
at Function.multilink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/axon/js/Property.js:533:12)
at new ISLCModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:108:14)
id: Bayes Chrome
Snapshot from 8/18/2021, 2:23:59 AM

----------------------------------

coulombs-law : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/phet-io-wrappers/phet-io-wrappers-tests.html?sim=coulombs-law
3 out of 4 tests passed. 1 failed.
SimTests: coulombs-law: iframe API failed:
Uncaught Error: Uncaught Error: Assertion failed: scientific notation is not supported: 1e-12
Error: Assertion failed: scientific notation is not supported: 1e-12
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/assert/js/assert.js:25:13)
at Object.numberOfDecimalPlaces (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/dot/js/Utils.js:835:17)
at CoulombsLawAtomicModel.snapToGrid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:427:36)
at CoulombsLawAtomicModel.getSumRadiusWithSeparation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:354:17)
at CoulombsLawAtomicModel.getObjectMaxPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:366:28)
at updateRange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:100:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:109:7
at new Multilink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/axon/js/Multilink.js:62:7)
at Function.multilink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/axon/js/Property.js:533:12)
at new ISLCModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:108:14)

Uncaught Error: Uncaught Error: Assertion failed: scientific notation is not supported: 1e-12Error: Assertion failed: scientific notation is not supported: 1e-12
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/assert/js/assert.js:25:13)
at Object.numberOfDecimalPlaces (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/dot/js/Utils.js:835:17)
at CoulombsLawAtomicModel.snapToGrid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:427:36)
at CoulombsLawAtomicModel.getSumRadiusWithSeparation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:354:17)
at CoulombsLawAtomicModel.getObjectMaxPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:366:28)
at updateRange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:100:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:109:7
at new Multilink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/axon/js/Multilink.js:62:7)
at Function.multilink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/axon/js/Property.js:533:12)
at new ISLCModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:108:14)
id: Bayes Chrome
Snapshot from 8/18/2021, 2:23:59 AM

----------------------------------

coulombs-law : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/coulombs-law/coulombs-law_en.html?continuousTest=%7B%22test%22%3A%5B%22coulombs-law%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1629275039864%22%2C%22timestamp%22%3A1629276636188%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: scientific notation is not supported: 1e-12
Error: Assertion failed: scientific notation is not supported: 1e-12
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/assert/js/assert.js:25:13)
at Object.numberOfDecimalPlaces (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/dot/js/Utils.js:835:17)
at CoulombsLawAtomicModel.snapToGrid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:427:36)
at CoulombsLawAtomicModel.getSumRadiusWithSeparation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:354:17)
at CoulombsLawAtomicModel.getObjectMaxPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:366:28)
at updateRange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:100:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:109:7
at new Multilink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/axon/js/Multilink.js:62:7)
at Function.multilink (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/axon/js/Property.js:533:12)
at new ISLCModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629275039864/inverse-square-law-common/js/model/ISLCModel.js:108:14)
id: Bayes Chrome
Snapshot from 8/18/2021, 2:23:59 AM
```

**Comment by zepumph** [comment]
Looks like this was solved over in https://github.com/phetsims/dot/issues/109 with https://github.com/phetsims/dot/commit/e585d101f7b238f25072baa3f2d38e55cc63293c.
