### ISSUE TITLE
Continuous testing error

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/coulombs-law#17]
```
coulombs-law : fuzz : require.js : load
Uncaught Error: Assertion failed: A circle needs a non-negative radius
Error: Assertion failed: A circle needs a non-negative radius
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1502486884656/assert/js/assert.js:22:13)
    at Circle.setRadius (https://bayes.colorado.edu/continuous-testing/snapshot-1502486884656/scenery/js/nodes/Circle.js?bust=1502487836048:239:17)
    at Circle.set radius [as radius] (https://bayes.colorado.edu/continuous-testing/snapshot-1502486884656/scenery/js/nodes/Circle.js?bust=1502487836048:253:39)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1502486884656/scenery/js/nodes/Node.js?bust=1502487836048:4900:25
    at u (https://bayes.colorado.edu/continuous-testing/snapshot-1502486884656/sherpa/lib/lodash-4.17.4.min.js?bust=1502487836048:5:432)
    at Function.ru (https://bayes.colorado.edu/continuous-testing/snapshot-1502486884656/sherpa/lib/lodash-4.17.4.min.js?bust=1502487836048:67:656)
    at Circle.mutate (https://bayes.colorado.edu/continuous-testing/snapshot-1502486884656/scenery/js/nodes/Node.js?bust=1502487836048:4887:9)
    at Circle.Path [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1502486884656/scenery/js/nodes/Path.js?bust=1502487836048:86:10)
    at new Circle (https://bayes.colorado.edu/continuous-testing/snapshot-1502486884656/scenery/js/nodes/Circle.js?bust=1502487836048:63:10)
    at ChargeNode.ObjectNode [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1502486884656/inverse-square-law-common/js/view/ObjectNode.js?bust=1502487836048:141:25)
Approximately 8/11/2017, 3:28:04 PM
coulombs-law : fuzz : require.js : run
Uncaught Error: Assertion failed: A circle needs a non-negative radius
Error: Assertion failed: A circle needs a non-negative radius
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1502486884656/assert/js/assert.js:22:13)
    at Circle.setRadius (https://bayes.colorado.edu/continuous-testing/snapshot-1502486884656/scenery/js/nodes/Circle.js?bust=1502487836048:239:17)
    at Circle.set radius [as radius] (https://bayes.colorado.edu/continuous-testing/snapshot-1502486884656/scenery/js/nodes/Circle.js?bust=1502487836048:253:39)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1502486884656/scenery/js/nodes/Node.js?bust=1502487836048:4900:25
    at u (https://bayes.colorado.edu/continuous-testing/snapshot-1502486884656/sherpa/lib/lodash-4.17.4.min.js?bust=1502487836048:5:432)
    at Function.ru (https://bayes.colorado.edu/continuous-testing/snapshot-1502486884656/sherpa/lib/lodash-4.17.4.min.js?bust=1502487836048:67:656)
    at Circle.mutate (https://bayes.colorado.edu/continuous-testing/snapshot-1502486884656/scenery/js/nodes/Node.js?bust=1502487836048:4887:9)
    at Circle.Path [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1502486884656/scenery/js/nodes/Path.js?bust=1502487836048:86:10)
    at new Circle (https://bayes.colorado.edu/continuous-testing/snapshot-1502486884656/scenery/js/nodes/Circle.js?bust=1502487836048:63:10)
    at ChargeNode.ObjectNode [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1502486884656/inverse-square-law-common/js/view/ObjectNode.js?bust=1502487836048:141:25)
Approximately 8/11/2017, 3:28:04 PM
```

**Comment by jessegreenberg** [comment]
@mbarlow12 can you please take a look?  Maybe just missing a pushed commit?

**Comment by mbarlow12** [comment]
This is pretty strange as the radius in each screen is constant. Even so, I've had the sim fuzzing with the latest update (https://github.com/phetsims/coulombs-law/commit/4fe1288b040066c919afe44d73f62512318b9a31) for >20min without errors. Closing.
