### ISSUE TITLE
CT: Tandem was required but not supplied

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/coulombs-law#67]
```
coulombs-law : phet-io-fuzz : require.js : load
Uncaught Error: Assertion failed: Tandem was required but not supplied
Error: Assertion failed: Tandem was required but not supplied
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1537216818522/assert/js/assert.js:22:13)
    at Tandem.addInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1537216818522/tandem/js/Tandem.js?bust=1537219026096:101:21)
    at Property.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1537216818522/tandem/js/PhetioObject.js?bust=1537219026096:151:19)
    at Property.PhetioObject [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1537216818522/tandem/js/PhetioObject.js?bust=1537219026096:80:12)
    at new Property (https://bayes.colorado.edu/continuous-testing/snapshot-1537216818522/axon/js/Property.js?bust=1537219026096:84:18)
    at CLMacroScreen.Screen [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1537216818522/joist/js/Screen.js?bust=1537219026096:130:27)
    at new CLMacroScreen (https://bayes.colorado.edu/continuous-testing/snapshot-1537216818522/coulombs-law/js/macro/CLMacroScreen.js?bust=1537219026096:40:12)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1537216818522/coulombs-law/js/coulombs-law-main.js?bust=1537219026096:47:5
    at Object.execCb (https://bayes.colorado.edu/continuous-testing/snapshot-1537216818522/sherpa/lib/require-2.1.11.js:1650:25)
    at Module.check (https://bayes.colorado.edu/continuous-testing/snapshot-1537216818522/sherpa/lib/require-2.1.11.js:866:35)
Approximately 9/17/2018, 2:40:18 PM
coulombs-law : phet-io-fuzz : require.js : run
Uncaught Error: Assertion failed: Tandem was required but not supplied
Error: Assertion failed: Tandem was required but not supplied
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1537216818522/assert/js/assert.js:22:13)
    at Tandem.addInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1537216818522/tandem/js/Tandem.js?bust=1537219026096:101:21)
    at Property.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1537216818522/tandem/js/PhetioObject.js?bust=1537219026096:151:19)
    at Property.PhetioObject [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1537216818522/tandem/js/PhetioObject.js?bust=1537219026096:80:12)
    at new Property (https://bayes.colorado.edu/continuous-testing/snapshot-1537216818522/axon/js/Property.js?bust=1537219026096:84:18)
    at CLMacroScreen.Screen [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1537216818522/joist/js/Screen.js?bust=1537219026096:130:27)
    at new CLMacroScreen (https://bayes.colorado.edu/continuous-testing/snapshot-1537216818522/coulombs-law/js/macro/CLMacroScreen.js?bust=1537219026096:40:12)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1537216818522/coulombs-law/js/coulombs-law-main.js?bust=1537219026096:47:5
    at Object.execCb (https://bayes.colorado.edu/continuous-testing/snapshot-1537216818522/sherpa/lib/require-2.1.11.js:1650:25)
    at Module.check (https://bayes.colorado.edu/continuous-testing/snapshot-1537216818522/sherpa/lib/require-2.1.11.js:866:35)
Approximately 9/17/2018, 2:40:18 PM
coulombs-law : phet-io-tests
7 out of 7 tests passed. 0 failed.

Approximately 9/17/2018, 2:40:18 PM
```

**Comment by zepumph** [comment]
Coulombs law is in a weird spot right now, because we seem to want to maintain it, i.e. for issues like https://github.com/phetsims/joist/issues/342, but it has not been run in phet-io mode really at all, so there are many issues with the current phet-io code. I did as much as I could today, but I have no idea how much  more tweaking there is to do right now. Until then, I guess we are stuck in this weird state. Tagging @samreid so he is aware.

**Comment by zepumph** [comment]
From https://github.com/phetsims/joist/issues/342:
>IMO it is better to have a sim that is partially outfitted with phet-io added to the phet-io list so that it can be maintained, rather than ignoring the sim and having it get more and more out of date.

**Comment by samreid** [comment]
I committed a fix that gets me through phet-io fuzz testing locally, and the wrapper unit tests are also passing.  So perhaps it is safe to close for now, but we can reopen this or a new issue if Bayes CT finds something else.

**Comment by zepumph** [comment]
Ha! I did many fixes, and then gave up only to find that there was but one left! Thanks for taking it to the finish line @samreid.
