### ISSUE TITLE
CT: AriaValueText

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/coulombs-law#76]
```
coulombs-law : accessibility-fuzz : built : load
Uncaught TypeError: s.createAriaValueText is not a function
TypeError: s.createAriaValueText is not a function
    at d (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/coulombs-law/build/phet/coulombs-law_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&accessibility:1968:389372)
    at e.link (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/coulombs-law/build/phet/coulombs-law_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&accessibility:1968:28843)
    at e.initializeAccessibleSlider (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/coulombs-law/build/phet/coulombs-law_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&accessibility:1968:389462)
    at e [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/coulombs-law/build/phet/coulombs-law_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&accessibility:1968:1820310)
    at new e (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/coulombs-law/build/phet/coulombs-law_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&accessibility:1968:1829011)
    at new e (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/coulombs-law/build/phet/coulombs-law_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&accessibility:1968:2229169)
    at e.createView (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/coulombs-law/build/phet/coulombs-law_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&accessibility:1968:2257704)
    at e.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/coulombs-law/build/phet/coulombs-law_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&accessibility:1968:1999449)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/coulombs-law/build/phet/coulombs-law_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&accessibility:1968:2384348)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/coulombs-law/build/phet/coulombs-law_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&accessibility:1968:2384425
id: Bayes Chrome
Approximately 10/26/2018, 12:20:35 AM
coulombs-law : accessibility-fuzz : built : run
Uncaught TypeError: s.createAriaValueText is not a function
TypeError: s.createAriaValueText is not a function
    at d (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/coulombs-law/build/phet/coulombs-law_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&accessibility:1968:389372)
    at e.link (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/coulombs-law/build/phet/coulombs-law_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&accessibility:1968:28843)
    at e.initializeAccessibleSlider (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/coulombs-law/build/phet/coulombs-law_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&accessibility:1968:389462)
    at e [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/coulombs-law/build/phet/coulombs-law_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&accessibility:1968:1820310)
    at new e (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/coulombs-law/build/phet/coulombs-law_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&accessibility:1968:1829011)
    at new e (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/coulombs-law/build/phet/coulombs-law_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&accessibility:1968:2229169)
    at e.createView (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/coulombs-law/build/phet/coulombs-law_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&accessibility:1968:2257704)
    at e.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/coulombs-law/build/phet/coulombs-law_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&accessibility:1968:1999449)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/coulombs-law/build/phet/coulombs-law_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&accessibility:1968:2384348)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/coulombs-law/build/phet/coulombs-law_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&accessibility:1968:2384425
id: Bayes Chrome
Approximately 10/26/2018, 12:20:35 AM
coulombs-law : fuzz : built-phet-io : load
Uncaught TypeError: s.createAriaValueText is not a function
TypeError: s.createAriaValueText is not a function
    at d (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892-phet-io/coulombs-law/build/phet-io/coulombs-law_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&phetioStandalone:1995:435294)
    at t.link (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892-phet-io/coulombs-law/build/phet-io/coulombs-law_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&phetioStandalone:1995:33794)
    at t.initializeAccessibleSlider (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892-phet-io/coulombs-law/build/phet-io/coulombs-law_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&phetioStandalone:1995:435384)
    at t [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892-phet-io/coulombs-law/build/phet-io/coulombs-law_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&phetioStandalone:1995:1855426)
    at new t (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892-phet-io/coulombs-law/build/phet-io/coulombs-law_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&phetioStandalone:1995:1864127)
    at new t (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892-phet-io/coulombs-law/build/phet-io/coulombs-law_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&phetioStandalone:1995:2264175)
    at t.createView (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892-phet-io/coulombs-law/build/phet-io/coulombs-law_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&phetioStandalone:1995:2292710)
    at t.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892-phet-io/coulombs-law/build/phet-io/coulombs-law_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&phetioStandalone:1995:2034455)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892-phet-io/coulombs-law/build/phet-io/coulombs-law_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&phetioStandalone:1995:2419256)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892-phet-io/coulombs-law/build/phet-io/coulombs-law_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&phetioStandalone:1995:2419333
id: Bayes Chrome
Approximately 10/26/2018, 12:20:35 AM
coulombs-law : fuzz : built-phet-io : run
Uncaught TypeError: s.createAriaValueText is not a function
TypeError: s.createAriaValueText is not a function
    at d (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892-phet-io/coulombs-law/build/phet-io/coulombs-law_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&phetioStandalone:1995:435294)
    at t.link (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892-phet-io/coulombs-law/build/phet-io/coulombs-law_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&phetioStandalone:1995:33794)
    at t.initializeAccessibleSlider (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892-phet-io/coulombs-law/build/phet-io/coulombs-law_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&phetioStandalone:1995:435384)
    at t [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892-phet-io/coulombs-law/build/phet-io/coulombs-law_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&phetioStandalone:1995:1855426)
    at new t (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892-phet-io/coulombs-law/build/phet-io/coulombs-law_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&phetioStandalone:1995:1864127)
    at new t (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892-phet-io/coulombs-law/build/phet-io/coulombs-law_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&phetioStandalone:1995:2264175)
    at t.createView (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892-phet-io/coulombs-law/build/phet-io/coulombs-law_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&phetioStandalone:1995:2292710)
    at t.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892-phet-io/coulombs-law/build/phet-io/coulombs-law_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&phetioStandalone:1995:2034455)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892-phet-io/coulombs-law/build/phet-io/coulombs-law_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&phetioStandalone:1995:2419256)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892-phet-io/coulombs-law/build/phet-io/coulombs-law_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&phetioStandalone:1995:2419333
id: Bayes Chrome
Approximately 10/26/2018, 12:20:35 AM
coulombs-law : phet-io-tests
7 out of 7 tests passed. 0 failed.

Approximately 10/26/2018, 12:20:35 AM
coulombs-law : xss-fuzz : load
Uncaught Error: Assertion failed: ISLCObjectNode subtypes must define an aria-valuetext creation function
Error: Assertion failed: ISLCObjectNode subtypes must define an aria-valuetext creation function
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/assert/js/assert.js:22:13)
    at ChargeNode.ISLCObjectNode [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/inverse-square-law-common/js/view/ISLCObjectNode.js?bust=1540538668404:128:15)
    at new ChargeNode (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/coulombs-law/js/common/view/ChargeNode.js?bust=1540538668404:80:20)
    at new CoulombsLawMacroView (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/coulombs-law/js/macro/view/CoulombsLawMacroView.js?bust=1540538668404:46:23)
    at CoulombsLawMacroScreen.createView (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/coulombs-law/js/macro/CoulombsLawMacroScreen.js?bust=1540538668404:45:34)
    at CoulombsLawMacroScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/joist/js/Screen.js?bust=1540538668404:251:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/joist/js/Sim.js?bust=1540538668404:780:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/joist/js/Sim.js?bust=1540538668404:788:27
id: Bayes Chrome
Approximately 10/26/2018, 12:20:35 AM
coulombs-law : xss-fuzz : run
Uncaught Error: Assertion failed: ISLCObjectNode subtypes must define an aria-valuetext creation function
Error: Assertion failed: ISLCObjectNode subtypes must define an aria-valuetext creation function
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/assert/js/assert.js:22:13)
    at ChargeNode.ISLCObjectNode [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/inverse-square-law-common/js/view/ISLCObjectNode.js?bust=1540538668404:128:15)
    at new ChargeNode (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/coulombs-law/js/common/view/ChargeNode.js?bust=1540538668404:80:20)
    at new CoulombsLawMacroView (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/coulombs-law/js/macro/view/CoulombsLawMacroView.js?bust=1540538668404:46:23)
    at CoulombsLawMacroScreen.createView (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/coulombs-law/js/macro/CoulombsLawMacroScreen.js?bust=1540538668404:45:34)
    at CoulombsLawMacroScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/joist/js/Screen.js?bust=1540538668404:251:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/joist/js/Sim.js?bust=1540538668404:780:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1540534835892/joist/js/Sim.js?bust=1540538668404:788:27
id: Bayes Chrome
Approximately 10/26/2018, 12:20:35 AM
```

**Comment by mbarlow12** [comment]
@KatieWoe that was from a previous commit from some dependencies. It appears that CT is passing in full now.

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe and @mbarlow12 since CL is all green on CT im going to close.
